stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-8
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-quick-marc:firebird-latest
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-ngvqv:firebird-helmcharts-mod-quick-marc
      version: 0.1.22
      answers:
        image.repository: docker.dev.folio.org/mod-quick-marc
        image.tag: firebird-latest
        postJob.enabled: true
      targetNamespace: firebird
      name: mod-quick-marc
timeout: 60
notification: {}
