openapi: 3.0.0
info:
  title: quickMARC MARC Specifications
  version: 1.0
servers:
  - url: /marc-specifications/
paths:
  /{recordType}/{fieldTag}:
    get:
      tags:
        - marc-specifications
      responses:
        '200':
          description: MARC specification successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/marcSpec'
        '400':
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '404':
          description: MARC specification with a given recordType and fieldTag not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      description: Get MARC specification by recordType and fieldTag
      operationId: getMarcSpecification
      parameters:
        - name: recordType
          in: path
          required: true
          description: Record type
          schema:
            type: string
            enum: [bibliographic,holdings,authority]
            example: bibliographic
        - name: fieldTag
          in: path
          required: true
          description: Field's tag
          schema:
            type: string
            pattern: ^[0-9]{3}$
            example: 008
components:
  schemas:
    error:
      type: object
    marcSpec:
      $ref: 'schemas/common.yaml#/marcSpecification'

