openapi: 3.0.0
info:
  title: quickMARC Record Editor
  version: 1.1.0
servers:
  - url: /records-editor/
paths:
  /records:
    get:
      tags:
        - records-editor
      responses:
        "200":
          description: MARC record successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/quickMarc"
        "400":
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        "404":
          description: MARC record with a given ID not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        "500":
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
      description: Get MARC record by externalId
      operationId: getRecordByExternalId
      parameters:
        - name: externalId
          in: query
          required: true
          description: UUID of the external that is related to the MARC record
          schema:
            $ref: "#/components/schemas/UUID"
        - name: lang
          in: query
          required: false
          description: Requested language. Optional. [lang=en]
          schema:
            type: string
            pattern: "[a-zA-Z]{2}"
            default: "en"
    post:
      tags:
        - records-editor
      responses:
        "201":
          description: MARC Record status created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/creationStatus"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        "500":
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/quickMarc"
        required: true
  /records/status:
    get:
      tags:
        - records-editor
      responses:
        '200':
          description: Status of MARC bibliographic record creation successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/creationStatus"
        '400':
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        '404':
          description: MARC record with a given ID not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
      description: Get status of MARC bibliographic record creation
      operationId: getRecordCreationStatus
      parameters:
        - name: qmRecordId
          in: query
          required: true
          description: UUID of ParsedRecord to be created
          schema:
            $ref: "#/components/schemas/UUID"
components:
  schemas:
    quickMarc:
      $ref: schemas/quickMarc.json
    creationStatus:
      $ref: schemas/creationStatus.json
    error:
      type: object
    UUID:
      type: string
      format: uuid
