openapi: 3.0.0
info:
  title: quickMARC Record Editor
  version: 5.5
servers:
  - url: /records-editor/
paths:
  /records:
    get:
      tags:
        - records-editor
      responses:
        '200':
          description: MARC record successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quickMarcView'
        '400':
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '404':
          description: MARC record with a given ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      description: Get MARC record by externalId
      operationId: getRecordByExternalId
      parameters:
        - name: externalId
          in: query
          required: true
          description: UUID of the external that is related to the MARC record
          schema:
            type: string
            format: uuid
    post:
      tags:
        - records-editor
      operationId: createNewRecord
      responses:
        '201':
          description: MARC Record status created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/creationStatus'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '422':
          description: MARC Record validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validationResult'
        '500':
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quickMarcCreate'
        required: true
  /records/{id}:
    put:
      tags:
        - records-editor
      responses:
        '202':
          description: MARC record accepted for updating
        '400':
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '409':
          description: Update failed due to optimistic locking
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '422':
          description: MARC Record validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validationResult'
        '500':
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      description: Edit MARC record
      operationId: putRecord
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quickMarcEdit'
        required: true
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The UUID of a record

  /records/status:
    get:
      tags:
        - records-editor
      responses:
        '200':
          description: Status of MARC bibliographic record creation successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/creationStatus'
        '400':
          description:
            Bad request, e.g. malformed request body or query parameter.
            Details of the error (e.g. name of the parameter or line/character number
            with malformed data) provided in the response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '404':
          description: MARC record with a given ID not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      description: Get status of MARC bibliographic record creation
      operationId: getRecordCreationStatus
      parameters:
        - name: qmRecordId
          in: query
          required: true
          description: UUID of ParsedRecord to be created
          schema:
            type: string
            format: uuid
  /links/suggestion:
    post:
      tags:
        - records-editor
      parameters:
        - name: authoritySearchParameter
          in: query
          required: false
          description: Authority field to search by
          schema:
            $ref: "#/components/schemas/authoritySearchParameter"
        - name: ignoreAutoLinkingEnabled
          in: query
          required: false
          description: Indicates if we need to ignore autoLinkingEnabled flag when filtering the fields for suggestions
          schema:
            type: boolean
            default: false
      responses:
        '201':
          description: MARC Record status created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quickMarcView'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quickMarcView'
        required: true
  /validate:
    post:
      tags:
        - records-validator
      responses:
        '200':
          description: MARC Record validation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validationResult'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: Internal server error, e.g. due to misconfiguration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/validatableRecord'
        required: true
components:
  schemas:
    quickMarcView:
      $ref: 'schemas/common.yaml#/quickMarcView'
    quickMarcCreate:
      $ref: 'schemas/common.yaml#/quickMarcCreate'
    quickMarcEdit:
      $ref: 'schemas/common.yaml#/quickMarcEdit'
    creationStatus:
      $ref: 'schemas/common.yaml#/creationStatus'
    validationResult:
      $ref: 'schemas/common.yaml#/validationResult'
    validatableRecord:
      $ref: 'schemas/common.yaml#/validatableRecord'
    error:
      type: object
    authoritySearchParameter:
      description: Authority search parameter for link suggestions
      type: string
      enum: [ ID, NATURAL_ID ]
      default: NATURAL_ID

