include:
  - infra-docker-compose.yml

services:
  mod-quick-marc:
    image: dev.folio/mod-quick-marc
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8081" # Allow Docker to dynamically assign a host port
    environment:
      ENV: ${ENV}
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - postgres
      - kafka-topic-init
    networks:
      - mod-quick-marc-local
    deploy:
      replicas: ${MODULE_REPLICAS:-1}
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"

networks:
  mod-quick-marc-local:
    driver: bridge
