package org.folio.qm.util;

public enum ErrorCodes {
  ILLEGAL_FIXED_LENGTH_CONTROL_FIELD,
  MISSED_001_FIELD,
  LEADER_AND_008_MISMATCHING,
  ILLEGAL_INDICATORS_NUMBER,
  ILLEGAL_SIZE_OF_INDICATOR
}
