package org.folio.qm.messaging.domain;

public enum QmEventTypes {

  QM_RECORD_UPDATED,
  QM_ERROR,
  QM_SRS_MARC_RECORD_UPDATED,
  QM_INVENTORY_INSTANCE_UPDATED,
  QM_INVENTORY_HOLDINGS_UPDATED,
  QM_COMPLETED
}
