#%RAML 1.0

title: quickMARC Editor Records
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://github.com/folio-org/mod-quick-marc

documentation:
  - title: quickMARC record API
    content: This documents the API calls that can be made to work with MARC records

types:
  quickMarcJson: !include schemas/quick_marc_json.json
  sample: !include examples/quick_marc_json.sample
  errors: !include raml-storage/raml-util/schemas/errors.schema
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  validate: !include raml-storage/raml-util/traits/validation.raml
  language: !include raml-storage/raml-util/traits/language.raml

/records-editor/records:
  displayName: quickMARC
  is: [language, validate]
  /{instanceId}:
    uriParameters:
      instanceId:
        description: The UUID of an instance associated with record
        type: UUID
    get:
      description: Get quickMARC record by instanceId
      responses:
        200:
          description: "MARC record successfully updated"
          body:
            application/json:
              type: quickMarcJson
              example:
                strict: false
                value: sample
        404:
          description: "MARC record with a given ID not found"
          body:
            application/json:
              example: "MARC record not found"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            application/json:
              example: "internal server error, contact administrator"
  /{id}:
    uriParameters:
      id:
        description: The UUID of a record
        type: UUID
    put:
      description: Edit quickMARC record
      body:
        application/json:
          type: quickMarcJson
          example:
            strict: false
            value: sample
      responses:
        204:
          description: "MARC record successfully updated"
          body:
            application/json:
              type: quickMarcJson
              example:
                strict: false
                value: sample
        404:
          description: "MARC record with a given ID not found"
          body:
            application/json:
              example: "MARC record not found"
        400:
          description: "Bad request, e.g. malformed request body or query parameter. Details of the error (e.g. name of the parameter or line/character number with malformed data) provided in the response."
          body:
            application/json:
              example: "Unable to update MARC record -- malformed JSON at 13:4"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            application/json:
              example: "internal server error, contact administrator"
